services:
  blackhole_core_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blackhole_core_api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: blackhole_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
