services:
  blackhole_core_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blackhole_core_api
    ports:
      - "8000:8000"
    environment:
      # Use the MongoDB URI from .env file or fall back to the local MongoDB container
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017/blackhole_db}
      - MONGO_URI_LOCAL=mongodb://mongo:27017/blackhole_db
      - DEBUG=false
      - MONGO_DB_NAME=blackhole_db
      - MONGO_COLLECTION_NAME=agent_outputs
      - PORT=8000
      - HOST=0.0.0.0
      - UPLOAD_DIR=/app/uploads
      - TEMP_DIR=/app/temp
      - PROCESSED_DIR=/app/processed
      - LOG_LEVEL=info
      - LOG_FILE=/app/logs/blackhole.log
      # CORS settings - update with your Netlify URL
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./temp:/app/temp
      - ./processed:/app/processed
      - ./.env:/app/.env
    depends_on:
      - mongo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongo:
    image: mongo:7.0
    container_name: blackhole_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mongo_data:
