[build]
  publish = "public"
  command = "node update_env.js"  # Run script to update env.js with environment variables

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#static"
