services:
  # A web service for the FastAPI backend
  - type: web
    name: blackhole-core-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        sync: false
      - key: CORS_ORIGINS
        value: "*"
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: false
