[build]
  publish = "dist"
  command = "bash ./build.sh"

[build.environment]
  PYTHON_VERSION = "3.11"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "uvicorn data.api.mcp_adapter:app --host 127.0.0.1 --port 8888"
  port = 8888
  publish = "dist"
